version: '3'

services:
  chess-ai:
    build:
      context: .
      dockerfile: dockerfile-chess-ai
    restart: always

  chess-server:
    build:
      context: .
      dockerfile: dockerfile-chess-server-client
#      dockerfile: dockerfile-chess-server
    depends_on:
      - chess-ai
    volumes:
    - chessgame_data:/usr/src/chessgame/server/chessgame_data
    ports:
      - "8080:8080"
    restart: always
volumes:
  chessgame_data: