package htwdd.chessgame.server.model

import com.j256.ormlite.field.DatabaseField
import com.j256.ormlite.table.DatabaseTable
import java.io.Serializable

/**
 * @author Felix Dimmel
 *
 * @property id The ID of this field (Autogenerated by SQLite database)
 * @property row Row number of the field
 * @property column Column number of the field
 *
 * @since 1.0.0
 */
@DatabaseTable(tableName = "Field")
class Field(
        @DatabaseField(generatedId = true)
        val id: Int = 0,
        @DatabaseField(canBeNull = false)
        var row: Int = 0,
        @DatabaseField(canBeNull = false)
        var column: Int = 0
) : Serializable {
    /**
     * @author Felix Dimmel
     *
     * @return the field as generic type pair
     *
     * @since 1.0.0
     */
    fun asPair(): Pair<Int, Int> {
        return Pair(row, column)
    }
}